version: "3.1"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db



  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DATABASE: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postqres
    ports:
        - "5050:80"


